title: Open Hardware Makers
email: ohwmakers@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mentoring & Training Program on Open Hardware inspired by Mozilla Open Leaders.
  Making Open Hardware the default everywhere, one project at a time.	
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohwmakers.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/ohm-logo.svg"
logo_png: "/assets/images/ohm-logo.png"
twitter_username: openHWmakers
github_username: ohwmakers
disquss_shortname: openhardware-space # copy the shortname provided in your disquss admin panel
api_url: https://mailservice-ohwmakers.herokuapp.com/api/sendemail #https://ohm-contact-service.herokuapp.com/api/sendemail # the contact form needs the api url
loader: false # for displaying page loader

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

collections_dir: collections
collections:
  stories:
    output: true
    permalink: "/stories/:path"
  mentors:
    output: true
    permalink: "/community/mentors/:path"
  experts:
    output: true
    permalink: "/community/experts/:path"
  members:
    output: true
    permalink: "/team/:path"
  projects:
    output: true

permalink: pretty

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2 # The number of links after the current page

autopages:
  enabled: true
  # Tag pages, omit to disable
  tags:
    enabled: true
    layouts:
      - stories.html
      - mentors.html
      - projects.html
    title: ":tag" # :tag is replaced by the tag name
    slugify:
      mode: "default" # :tag is slugified.
      case: false

  categories:
    enabled: false
  collections:
    enabled: false

sass:
  sass_dir: /assets/sass
  style: compressed
  sourcemap: always
  # load_paths:
  # - /assets/sass/
  #   - node_modules/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
